version: "3"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/surveys_system_api
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env
  db:
    image: postgres:15
      # Внешний том(volume) и место где он будет подключен внутри контейнера
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    environment:
        # Учетные данные, которые можно будет переопределить
      - POSTGRES_USER=surveysystemapiuser
      - POSTGRES_PASSWORD=Qwedsa22
      - POSTGRES_DB=surveysystemapi

volumes:
  postgres_volume:
