# Generated by Django 4.1.4 on 2022-12-29 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='название')),
                ('date_start', models.DateTimeField(verbose_name='дата старта')),
                ('date_end', models.DateTimeField(verbose_name='дата окончания')),
                ('description', models.CharField(max_length=200, verbose_name='описание')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200, verbose_name='текст вопроса')),
                ('question_type', models.CharField(choices=[('text', 'Ответ текстом'), ('one_option', 'Ответ с выбором одного варианта ответа'), ('many_options', 'Ответ с выбором нескольких вариантов ответа')], max_length=200, verbose_name='тип вопроса')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='app_surveys.survey', verbose_name='опрос')),
            ],
        ),
    ]
