# Generated by Django 4.1.4 on 2023-01-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_surveys', '0003_choice_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_text',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='текст ответа'),
        ),
    ]
