# Generated by Django 4.1.4 on 2023-01-03 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_surveys', '0004_alter_answer_answer_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='app_surveys.choice', verbose_name='выбор'),
        ),
    ]
